remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Matthew Schaub ePortfolio"
description: "SNHU CS-499 - Computer Science Capstone"

show_downloads: false
github:
  repository_url: "https://github.com/mschaub62/mschaub62.github.io"

